### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [Neumi/ethersweep#1]
Hello!

I found this project from https://hackaday.com/2022/09/07/ethersweep-an-easy-to-deploy-ethernet-connected-stepper-controller/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and design files in any purpose?
It would be great to see any popular open source license.

**Comment by Neumi** [comment]
resolved

**Comment by vazhnov** [comment]
Sad this is not some popular opensource license.
But anyway it is better than nothing.
@Neumi , thank you!

**Comment by Neumi** [comment]
It is basically MIT, except for the addition that I want to keep a hand on the commercial manufacturing of the hardware. Everything else is MIT for (I guess) a good reason. I you wish for a more open license, let me know :)
